1.

In [13]:
import numpy as np

A = np.array([[0, 1, -2], [2, 3, -1], [1, -1, 5]])
B = np.array([[1, -1, 2, 1], [2, -2, 2, -2], [-1, 2, 1, 2]])
C = np.array([[2], [0], [1], [-4]])

print(A.dot(B), '\n')
print(B.dot(C), '\n')
print(np.matrix.transpose(B), '\n')
print(np.matrix.transpose(B).dot(A), '\n')
print(np.matrix.transpose(C).dot(np.matrix.transpose(B)), '\n')

[[  4  -6   0  -6]
 [  9 -10   9  -6]
 [ -6  11   5  13]] 

[[ 0]
 [14]
 [-9]] 

[[ 1  2 -1]
 [-1 -2  2]
 [ 2  2  1]
 [ 1 -2  2]] 

[[ 3  8 -9]
 [-2 -9 14]
 [ 5  7 -1]
 [-2 -7 10]] 

[[ 0 14 -9]] 



In [10]:
np.matrix.transpose(A)

array([[ 0,  2,  1],
       [ 1,  3, -1],
       [-2, -1,  5]])