In [8]:
import numpy as np
import scipy.linalg

A1 = np.array([[0, 2, -3, 4], [0, 0, -5, -1], [5, -1, -2, 0], [-2, 0, 4, 6]])
A2 = np.array([[1, 2, -1, 4], [0, -1, 5, 8], [2, 3, 1, 4], [1, -1, 6, 4]])
A3 = np.array([[2, 4, -2, 0], [3, 7, 5, -4], [-1, 2, -2, 5], [6, 1, 0, 2]])
A4 = np.array([[0, 2, 3, 1], [0, 4, -1, 5], [2, 0, 3, 1], [1, -4, 5, 6]])

for matrix_num, matrix_obj in enumerate((A1, A2, A3, A4), 1):
    P, L, U  = scipy.linalg.lu(matrix_obj)
    print(f'MATRIX A{matrix_num}'+'-'*40)
    print(f'P = {P}\nL = {L}\nU = {U}')

MATRIX A1----------------------------------------
P = [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]
L = [[ 1.    0.    0.    0.  ]
 [ 0.    1.    0.    0.  ]
 [ 0.    0.    1.    0.  ]
 [-0.4  -0.2  -0.52  1.  ]]
U = [[ 5.   -1.   -2.    0.  ]
 [ 0.    2.   -3.    4.  ]
 [ 0.    0.   -5.   -1.  ]
 [ 0.    0.    0.    6.28]]
MATRIX A2----------------------------------------
P = [[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]
L = [[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 0.          0.4         1.          0.        ]
 [ 0.5        -0.2        -0.14285714  1.        ]]
U = [[ 2.          3.          1.          4.        ]
 [ 0.         -2.5         5.5         2.        ]
 [ 0.          0.          2.8         7.2       ]
 [ 0.          0.          0.          3.42857143]]
MATRIX A3----------------------------------------
P = [[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]
L = [[ 1.  